name: publish-staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  generate: 
    name: "Generate site"
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4

      - name: "Generate static HTML"
        uses: pillar-markup/Foliage@master
        with:
          source: site
          retention-days: 5
        
      - name: Replace baseUri
        run: |
          sed -i 's|"baseUri" : "https://pharo.org"|"baseUri" : "https://staging.pharo.org"|g' generated/FoliageConfig.json

      - name: "Upload to server"
        uses: up9cloud/action-rsync@v1.3
        env:
          KEY: ${{ secrets.SERVER_SSH_KEY }}
          USER: ${{ secrets.REMOTE_USER }}
          HOST: ${{ secrets.REMOTE_HOST }}
          TARGET: ${{ secrets.REMOTE_STAGING_TARGET }}
          SOURCE: generated/
